# Generated by Django 3.0.5 on 2020-04-25 15:41

import crm.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('tax_id', models.CharField(blank=True, max_length=25, verbose_name='Tax ID')),
                ('phone_number', models.CharField(blank=True, max_length=25, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('registration_time', models.DateTimeField(blank=True, null=True, verbose_name='Registration Time')),
                ('expiration_time', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Time')),
                ('remark', models.TextField(blank=True, max_length=400, verbose_name='Remark')),
                ('related_file', models.FileField(blank=True, null=True, upload_to=crm.models.get_directory_path, verbose_name='Related File')),
                ('related_image', models.ImageField(blank=True, null=True, upload_to=crm.models.get_directory_path, verbose_name='Related Image')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_person_parent_set', to='crm.Person', verbose_name='Parent')),
                ('related_salesperson', models.ManyToManyField(blank=True, related_name='crm_person_related_salesperson_set', to='crm.Person', verbose_name='Related Salespersons')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': [django.db.models.functions.text.Concat('name', django.db.models.expressions.Value(' ('), 'code', django.db.models.expressions.Value(')'))],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['id'], name='crm_person_id_77f6da_idx'),
        ),
    ]
