# Generated by Django 3.0.5 on 2020-04-23 09:06

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to=crm.models.get_directory_path, verbose_name='Related File'),
        ),
        migrations.AlterField(
            model_name='person',
            name='related_image',
            field=models.ImageField(blank=True, null=True, upload_to=crm.models.get_directory_path, verbose_name='Related Image'),
        ),
    ]
